### Recuperar todas las películas
GET http://localhost:1234/movies


### Recuperar películas por ID
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar películas por genero
GET http://localhost:1234/movies?year=2010

### Postear una película
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Peli5",
    "year": 1994,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": ["Drama"],
    "rate": 9.0
  }

### Actualizar una película
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 1995
}

### Delete una película
DELETE http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0